apiVersion: apps/v1
kind: Deployment
metadata:
  name: test1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test1
  template:
    metadata:
      labels:
        app: test1
    spec:
      containers:
      - image: nurlan1992/test1:test1-7784bf1
        name: test1
        ports:
        - containerPort: 5000
